name: KeepChunks
version: 1.7.3
api-version: 1.18
description: The most powerful chunk loading plugin!
author: Geitenijs
website: https://www.spigotmc.org/resources/23307
load: POSTWORLD

softdepend: [WorldEdit, FastAsyncWorldEdit, WorldGuard, Multiverse-Core, MultiWorld, My_Worlds]

main: com.geitenijs.keepchunks.Main

commands:
  keepchunks:
    description: Keep chunks loaded.
  kc:
    description: Keep chunks loaded.

permissions:
  keepchunks.help:
    default: op
  keepchunks.reload:
    default: op
  keepchunks.list:
    default: op
  keepchunks.chunkinfo:
    default: op
  keepchunks.keepchunk:
    default: op
  keepchunks.keepregion:
    default: op
  keepchunks.keeprail:
    default: op
  keepchunks.releaseall:
    default: op
  keepchunks.releasechunk:
    default: op
  keepchunks.releaseregion:
    default: op
  keepchunks.releaserail:
    default: op
  keepchunks.notify.update:
    default: op